# Generated by Django 5.0.7 on 2024-07-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobpost_date_jobpost_decription_jobpost_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='decription',
            new_name='description',
        ),
    ]
