# Generated by Django 5.0.7 on 2024-07-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
