# Generated by Django 5.0.7 on 2024-07-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobpost_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='image',
            field=models.ImageField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
