# Generated by Django 5.0.7 on 2024-07-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='image',
        ),
    ]
